/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TratamentosRouteImport } from './routes/tratamentos'
import { Route as ReativacaoRouteImport } from './routes/reativacao'
import { Route as ProntuarioRouteImport } from './routes/prontuario'
import { Route as PainelDentistaRouteImport } from './routes/painel-dentista'
import { Route as PainelComercialRouteImport } from './routes/painel-comercial'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DisparosRouteImport } from './routes/disparos'
import { Route as DentistasRouteImport } from './routes/dentistas'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComissoesRouteImport } from './routes/comissoes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const TratamentosRoute = TratamentosRouteImport.update({
  id: '/tratamentos',
  path: '/tratamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReativacaoRoute = ReativacaoRouteImport.update({
  id: '/reativacao',
  path: '/reativacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntuarioRoute = ProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelDentistaRoute = PainelDentistaRouteImport.update({
  id: '/painel-dentista',
  path: '/painel-dentista',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelComercialRoute = PainelComercialRouteImport.update({
  id: '/painel-comercial',
  path: '/painel-comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparosRoute = DisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistasRoute = DentistasRouteImport.update({
  id: '/dentistas',
  path: '/dentistas',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComissoesRoute = ComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/canais': typeof CanaisRoute
  '/chat': typeof ChatRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dentistas': typeof DentistasRoute
  '/disparos': typeof DisparosRoute
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pacientes': typeof PacientesRoute
  '/painel-comercial': typeof PainelComercialRoute
  '/painel-dentista': typeof PainelDentistaRoute
  '/prontuario': typeof ProntuarioRoute
  '/reativacao': typeof ReativacaoRoute
  '/tratamentos': typeof TratamentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/canais': typeof CanaisRoute
  '/chat': typeof ChatRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dentistas': typeof DentistasRoute
  '/disparos': typeof DisparosRoute
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pacientes': typeof PacientesRoute
  '/painel-comercial': typeof PainelComercialRoute
  '/painel-dentista': typeof PainelDentistaRoute
  '/prontuario': typeof ProntuarioRoute
  '/reativacao': typeof ReativacaoRoute
  '/tratamentos': typeof TratamentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/canais': typeof CanaisRoute
  '/chat': typeof ChatRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dentistas': typeof DentistasRoute
  '/disparos': typeof DisparosRoute
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pacientes': typeof PacientesRoute
  '/painel-comercial': typeof PainelComercialRoute
  '/painel-dentista': typeof PainelDentistaRoute
  '/prontuario': typeof ProntuarioRoute
  '/reativacao': typeof ReativacaoRoute
  '/tratamentos': typeof TratamentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/automacoes'
    | '/campanhas'
    | '/canais'
    | '/chat'
    | '/comissoes'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dentistas'
    | '/disparos'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/integracoes'
    | '/login'
    | '/metricas'
    | '/orcamentos'
    | '/pacientes'
    | '/painel-comercial'
    | '/painel-dentista'
    | '/prontuario'
    | '/reativacao'
    | '/tratamentos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/automacoes'
    | '/campanhas'
    | '/canais'
    | '/chat'
    | '/comissoes'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dentistas'
    | '/disparos'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/integracoes'
    | '/login'
    | '/metricas'
    | '/orcamentos'
    | '/pacientes'
    | '/painel-comercial'
    | '/painel-dentista'
    | '/prontuario'
    | '/reativacao'
    | '/tratamentos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/analytics'
    | '/automacoes'
    | '/campanhas'
    | '/canais'
    | '/chat'
    | '/comissoes'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dentistas'
    | '/disparos'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/integracoes'
    | '/login'
    | '/metricas'
    | '/orcamentos'
    | '/pacientes'
    | '/painel-comercial'
    | '/painel-dentista'
    | '/prontuario'
    | '/reativacao'
    | '/tratamentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AutomacoesRoute: typeof AutomacoesRoute
  CampanhasRoute: typeof CampanhasRoute
  CanaisRoute: typeof CanaisRoute
  ChatRoute: typeof ChatRoute
  ComissoesRoute: typeof ComissoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContatosRoute: typeof ContatosRoute
  CrmRoute: typeof CrmRoute
  DentistasRoute: typeof DentistasRoute
  DisparosRoute: typeof DisparosRoute
  EquipeRoute: typeof EquipeRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  MetricasRoute: typeof MetricasRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PacientesRoute: typeof PacientesRoute
  PainelComercialRoute: typeof PainelComercialRoute
  PainelDentistaRoute: typeof PainelDentistaRoute
  ProntuarioRoute: typeof ProntuarioRoute
  ReativacaoRoute: typeof ReativacaoRoute
  TratamentosRoute: typeof TratamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tratamentos': {
      id: '/tratamentos'
      path: '/tratamentos'
      fullPath: '/tratamentos'
      preLoaderRoute: typeof TratamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reativacao': {
      id: '/reativacao'
      path: '/reativacao'
      fullPath: '/reativacao'
      preLoaderRoute: typeof ReativacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prontuario': {
      id: '/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof ProntuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-dentista': {
      id: '/painel-dentista'
      path: '/painel-dentista'
      fullPath: '/painel-dentista'
      preLoaderRoute: typeof PainelDentistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-comercial': {
      id: '/painel-comercial'
      path: '/painel-comercial'
      fullPath: '/painel-comercial'
      preLoaderRoute: typeof PainelComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparos': {
      id: '/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof DisparosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentistas': {
      id: '/dentistas'
      path: '/dentistas'
      fullPath: '/dentistas'
      preLoaderRoute: typeof DentistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comissoes': {
      id: '/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof ComissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AnalyticsRoute: AnalyticsRoute,
  AutomacoesRoute: AutomacoesRoute,
  CampanhasRoute: CampanhasRoute,
  CanaisRoute: CanaisRoute,
  ChatRoute: ChatRoute,
  ComissoesRoute: ComissoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContatosRoute: ContatosRoute,
  CrmRoute: CrmRoute,
  DentistasRoute: DentistasRoute,
  DisparosRoute: DisparosRoute,
  EquipeRoute: EquipeRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  MetricasRoute: MetricasRoute,
  OrcamentosRoute: OrcamentosRoute,
  PacientesRoute: PacientesRoute,
  PainelComercialRoute: PainelComercialRoute,
  PainelDentistaRoute: PainelDentistaRoute,
  ProntuarioRoute: ProntuarioRoute,
  ReativacaoRoute: ReativacaoRoute,
  TratamentosRoute: TratamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
