/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReativacaoRouteImport } from './routes/reativacao'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const ReativacaoRoute = ReativacaoRouteImport.update({
  id: '/reativacao',
  path: '/reativacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campanhas': typeof CampanhasRoute
  '/canais': typeof CanaisRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/funil': typeof FunilRoute
  '/integracoes': typeof IntegracoesRoute
  '/reativacao': typeof ReativacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campanhas': typeof CampanhasRoute
  '/canais': typeof CanaisRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/funil': typeof FunilRoute
  '/integracoes': typeof IntegracoesRoute
  '/reativacao': typeof ReativacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campanhas': typeof CampanhasRoute
  '/canais': typeof CanaisRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/funil': typeof FunilRoute
  '/integracoes': typeof IntegracoesRoute
  '/reativacao': typeof ReativacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campanhas'
    | '/canais'
    | '/chat'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/financeiro'
    | '/funil'
    | '/integracoes'
    | '/reativacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/campanhas'
    | '/canais'
    | '/chat'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/financeiro'
    | '/funil'
    | '/integracoes'
    | '/reativacao'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campanhas'
    | '/canais'
    | '/chat'
    | '/configuracoes'
    | '/crm'
    | '/equipe'
    | '/financeiro'
    | '/funil'
    | '/integracoes'
    | '/reativacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampanhasRoute: typeof CampanhasRoute
  CanaisRoute: typeof CanaisRoute
  ChatRoute: typeof ChatRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CrmRoute: typeof CrmRoute
  EquipeRoute: typeof EquipeRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FunilRoute: typeof FunilRoute
  IntegracoesRoute: typeof IntegracoesRoute
  ReativacaoRoute: typeof ReativacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reativacao': {
      id: '/reativacao'
      path: '/reativacao'
      fullPath: '/reativacao'
      preLoaderRoute: typeof ReativacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampanhasRoute: CampanhasRoute,
  CanaisRoute: CanaisRoute,
  ChatRoute: ChatRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CrmRoute: CrmRoute,
  EquipeRoute: EquipeRoute,
  FinanceiroRoute: FinanceiroRoute,
  FunilRoute: FunilRoute,
  IntegracoesRoute: IntegracoesRoute,
  ReativacaoRoute: ReativacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
