/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TratamentosRouteImport } from './routes/tratamentos'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SbSignupRouteImport } from './routes/sb-signup'
import { Route as SbPacientesRouteImport } from './routes/sb-pacientes'
import { Route as SbLoginRouteImport } from './routes/sb-login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosClinicosRouteImport } from './routes/relatorios-clinicos'
import { Route as ReativacaoRouteImport } from './routes/reativacao'
import { Route as ProntuarioRouteImport } from './routes/prontuario'
import { Route as ProcedimentosRouteImport } from './routes/procedimentos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PainelDentistaRouteImport } from './routes/painel-dentista'
import { Route as PainelComercialRouteImport } from './routes/painel-comercial'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as MinhaAssinaturaRouteImport } from './routes/minha-assinatura'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ExamesRouteImport } from './routes/exames'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DisparosRouteImport } from './routes/disparos'
import { Route as DentistasRouteImport } from './routes/dentistas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComissoesRouteImport } from './routes/comissoes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesAgendaRouteImport } from './routes/configuracoes.agenda'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentosRoute = TratamentosRouteImport.update({
  id: '/tratamentos',
  path: '/tratamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SbSignupRoute = SbSignupRouteImport.update({
  id: '/sb-signup',
  path: '/sb-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SbPacientesRoute = SbPacientesRouteImport.update({
  id: '/sb-pacientes',
  path: '/sb-pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const SbLoginRoute = SbLoginRouteImport.update({
  id: '/sb-login',
  path: '/sb-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosClinicosRoute = RelatoriosClinicosRouteImport.update({
  id: '/relatorios-clinicos',
  path: '/relatorios-clinicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReativacaoRoute = ReativacaoRouteImport.update({
  id: '/reativacao',
  path: '/reativacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntuarioRoute = ProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosRoute = ProcedimentosRouteImport.update({
  id: '/procedimentos',
  path: '/procedimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelDentistaRoute = PainelDentistaRouteImport.update({
  id: '/painel-dentista',
  path: '/painel-dentista',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelComercialRoute = PainelComercialRouteImport.update({
  id: '/painel-comercial',
  path: '/painel-comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAssinaturaRoute = MinhaAssinaturaRouteImport.update({
  id: '/minha-assinatura',
  path: '/minha-assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesRoute = ExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparosRoute = DisparosRouteImport.update({
  id: '/disparos',
  path: '/disparos',
  getParentRoute: () => rootRouteImport,
} as any)
const DentistasRoute = DentistasRouteImport.update({
  id: '/dentistas',
  path: '/dentistas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComissoesRoute = ComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesAgendaRoute = ConfiguracoesAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ConfiguracoesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/atendimento': typeof AtendimentoRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/canais': typeof CanaisRoute
  '/chat': typeof ChatRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/dentistas': typeof DentistasRoute
  '/disparos': typeof DisparosRoute
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRoute
  '/exames': typeof ExamesRoute
  '/financeiro': typeof FinanceiroRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pacientes': typeof PacientesRoute
  '/painel-comercial': typeof PainelComercialRoute
  '/painel-dentista': typeof PainelDentistaRoute
  '/perfil': typeof PerfilRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/prontuario': typeof ProntuarioRoute
  '/reativacao': typeof ReativacaoRoute
  '/relatorios-clinicos': typeof RelatoriosClinicosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sb-login': typeof SbLoginRoute
  '/sb-pacientes': typeof SbPacientesRoute
  '/sb-signup': typeof SbSignupRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/tratamentos': typeof TratamentosRoute
  '/usuarios': typeof UsuariosRoute
  '/configuracoes/agenda': typeof ConfiguracoesAgendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/atendimento': typeof AtendimentoRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/canais': typeof CanaisRoute
  '/chat': typeof ChatRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/dentistas': typeof DentistasRoute
  '/disparos': typeof DisparosRoute
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRoute
  '/exames': typeof ExamesRoute
  '/financeiro': typeof FinanceiroRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pacientes': typeof PacientesRoute
  '/painel-comercial': typeof PainelComercialRoute
  '/painel-dentista': typeof PainelDentistaRoute
  '/perfil': typeof PerfilRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/prontuario': typeof ProntuarioRoute
  '/reativacao': typeof ReativacaoRoute
  '/relatorios-clinicos': typeof RelatoriosClinicosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sb-login': typeof SbLoginRoute
  '/sb-pacientes': typeof SbPacientesRoute
  '/sb-signup': typeof SbSignupRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/tratamentos': typeof TratamentosRoute
  '/usuarios': typeof UsuariosRoute
  '/configuracoes/agenda': typeof ConfiguracoesAgendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/analytics': typeof AnalyticsRoute
  '/atendimento': typeof AtendimentoRoute
  '/automacoes': typeof AutomacoesRoute
  '/campanhas': typeof CampanhasRoute
  '/canais': typeof CanaisRoute
  '/chat': typeof ChatRoute
  '/comissoes': typeof ComissoesRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contatos': typeof ContatosRoute
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/dentistas': typeof DentistasRoute
  '/disparos': typeof DisparosRoute
  '/equipe': typeof EquipeRoute
  '/estoque': typeof EstoqueRoute
  '/exames': typeof ExamesRoute
  '/financeiro': typeof FinanceiroRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/metricas': typeof MetricasRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/orcamentos': typeof OrcamentosRoute
  '/pacientes': typeof PacientesRoute
  '/painel-comercial': typeof PainelComercialRoute
  '/painel-dentista': typeof PainelDentistaRoute
  '/perfil': typeof PerfilRoute
  '/procedimentos': typeof ProcedimentosRoute
  '/prontuario': typeof ProntuarioRoute
  '/reativacao': typeof ReativacaoRoute
  '/relatorios-clinicos': typeof RelatoriosClinicosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sb-login': typeof SbLoginRoute
  '/sb-pacientes': typeof SbPacientesRoute
  '/sb-signup': typeof SbSignupRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRoute
  '/tratamentos': typeof TratamentosRoute
  '/usuarios': typeof UsuariosRoute
  '/configuracoes/agenda': typeof ConfiguracoesAgendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/atendimento'
    | '/automacoes'
    | '/campanhas'
    | '/canais'
    | '/chat'
    | '/comissoes'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dashboard'
    | '/dentistas'
    | '/disparos'
    | '/equipe'
    | '/estoque'
    | '/exames'
    | '/financeiro'
    | '/integracoes'
    | '/login'
    | '/metricas'
    | '/minha-assinatura'
    | '/orcamentos'
    | '/pacientes'
    | '/painel-comercial'
    | '/painel-dentista'
    | '/perfil'
    | '/procedimentos'
    | '/prontuario'
    | '/reativacao'
    | '/relatorios-clinicos'
    | '/reset-password'
    | '/sb-login'
    | '/sb-pacientes'
    | '/sb-signup'
    | '/signup'
    | '/super-admin'
    | '/tratamentos'
    | '/usuarios'
    | '/configuracoes/agenda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/analytics'
    | '/atendimento'
    | '/automacoes'
    | '/campanhas'
    | '/canais'
    | '/chat'
    | '/comissoes'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dashboard'
    | '/dentistas'
    | '/disparos'
    | '/equipe'
    | '/estoque'
    | '/exames'
    | '/financeiro'
    | '/integracoes'
    | '/login'
    | '/metricas'
    | '/minha-assinatura'
    | '/orcamentos'
    | '/pacientes'
    | '/painel-comercial'
    | '/painel-dentista'
    | '/perfil'
    | '/procedimentos'
    | '/prontuario'
    | '/reativacao'
    | '/relatorios-clinicos'
    | '/reset-password'
    | '/sb-login'
    | '/sb-pacientes'
    | '/sb-signup'
    | '/signup'
    | '/super-admin'
    | '/tratamentos'
    | '/usuarios'
    | '/configuracoes/agenda'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/analytics'
    | '/atendimento'
    | '/automacoes'
    | '/campanhas'
    | '/canais'
    | '/chat'
    | '/comissoes'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/dashboard'
    | '/dentistas'
    | '/disparos'
    | '/equipe'
    | '/estoque'
    | '/exames'
    | '/financeiro'
    | '/integracoes'
    | '/login'
    | '/metricas'
    | '/minha-assinatura'
    | '/orcamentos'
    | '/pacientes'
    | '/painel-comercial'
    | '/painel-dentista'
    | '/perfil'
    | '/procedimentos'
    | '/prontuario'
    | '/reativacao'
    | '/relatorios-clinicos'
    | '/reset-password'
    | '/sb-login'
    | '/sb-pacientes'
    | '/sb-signup'
    | '/signup'
    | '/super-admin'
    | '/tratamentos'
    | '/usuarios'
    | '/configuracoes/agenda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AtendimentoRoute: typeof AtendimentoRoute
  AutomacoesRoute: typeof AutomacoesRoute
  CampanhasRoute: typeof CampanhasRoute
  CanaisRoute: typeof CanaisRoute
  ChatRoute: typeof ChatRoute
  ComissoesRoute: typeof ComissoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  ContatosRoute: typeof ContatosRoute
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  DentistasRoute: typeof DentistasRoute
  DisparosRoute: typeof DisparosRoute
  EquipeRoute: typeof EquipeRoute
  EstoqueRoute: typeof EstoqueRoute
  ExamesRoute: typeof ExamesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  MetricasRoute: typeof MetricasRoute
  MinhaAssinaturaRoute: typeof MinhaAssinaturaRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PacientesRoute: typeof PacientesRoute
  PainelComercialRoute: typeof PainelComercialRoute
  PainelDentistaRoute: typeof PainelDentistaRoute
  PerfilRoute: typeof PerfilRoute
  ProcedimentosRoute: typeof ProcedimentosRoute
  ProntuarioRoute: typeof ProntuarioRoute
  ReativacaoRoute: typeof ReativacaoRoute
  RelatoriosClinicosRoute: typeof RelatoriosClinicosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SbLoginRoute: typeof SbLoginRoute
  SbPacientesRoute: typeof SbPacientesRoute
  SbSignupRoute: typeof SbSignupRoute
  SignupRoute: typeof SignupRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TratamentosRoute: typeof TratamentosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamentos': {
      id: '/tratamentos'
      path: '/tratamentos'
      fullPath: '/tratamentos'
      preLoaderRoute: typeof TratamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sb-signup': {
      id: '/sb-signup'
      path: '/sb-signup'
      fullPath: '/sb-signup'
      preLoaderRoute: typeof SbSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sb-pacientes': {
      id: '/sb-pacientes'
      path: '/sb-pacientes'
      fullPath: '/sb-pacientes'
      preLoaderRoute: typeof SbPacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sb-login': {
      id: '/sb-login'
      path: '/sb-login'
      fullPath: '/sb-login'
      preLoaderRoute: typeof SbLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios-clinicos': {
      id: '/relatorios-clinicos'
      path: '/relatorios-clinicos'
      fullPath: '/relatorios-clinicos'
      preLoaderRoute: typeof RelatoriosClinicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reativacao': {
      id: '/reativacao'
      path: '/reativacao'
      fullPath: '/reativacao'
      preLoaderRoute: typeof ReativacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prontuario': {
      id: '/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof ProntuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos': {
      id: '/procedimentos'
      path: '/procedimentos'
      fullPath: '/procedimentos'
      preLoaderRoute: typeof ProcedimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-dentista': {
      id: '/painel-dentista'
      path: '/painel-dentista'
      fullPath: '/painel-dentista'
      preLoaderRoute: typeof PainelDentistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-comercial': {
      id: '/painel-comercial'
      path: '/painel-comercial'
      fullPath: '/painel-comercial'
      preLoaderRoute: typeof PainelComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-assinatura': {
      id: '/minha-assinatura'
      path: '/minha-assinatura'
      fullPath: '/minha-assinatura'
      preLoaderRoute: typeof MinhaAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames': {
      id: '/exames'
      path: '/exames'
      fullPath: '/exames'
      preLoaderRoute: typeof ExamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparos': {
      id: '/disparos'
      path: '/disparos'
      fullPath: '/disparos'
      preLoaderRoute: typeof DisparosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dentistas': {
      id: '/dentistas'
      path: '/dentistas'
      fullPath: '/dentistas'
      preLoaderRoute: typeof DentistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comissoes': {
      id: '/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof ComissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/agenda': {
      id: '/configuracoes/agenda'
      path: '/agenda'
      fullPath: '/configuracoes/agenda'
      preLoaderRoute: typeof ConfiguracoesAgendaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesAgendaRoute: typeof ConfiguracoesAgendaRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesAgendaRoute: ConfiguracoesAgendaRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AnalyticsRoute: AnalyticsRoute,
  AtendimentoRoute: AtendimentoRoute,
  AutomacoesRoute: AutomacoesRoute,
  CampanhasRoute: CampanhasRoute,
  CanaisRoute: CanaisRoute,
  ChatRoute: ChatRoute,
  ComissoesRoute: ComissoesRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  ContatosRoute: ContatosRoute,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  DentistasRoute: DentistasRoute,
  DisparosRoute: DisparosRoute,
  EquipeRoute: EquipeRoute,
  EstoqueRoute: EstoqueRoute,
  ExamesRoute: ExamesRoute,
  FinanceiroRoute: FinanceiroRoute,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  MetricasRoute: MetricasRoute,
  MinhaAssinaturaRoute: MinhaAssinaturaRoute,
  OrcamentosRoute: OrcamentosRoute,
  PacientesRoute: PacientesRoute,
  PainelComercialRoute: PainelComercialRoute,
  PainelDentistaRoute: PainelDentistaRoute,
  PerfilRoute: PerfilRoute,
  ProcedimentosRoute: ProcedimentosRoute,
  ProntuarioRoute: ProntuarioRoute,
  ReativacaoRoute: ReativacaoRoute,
  RelatoriosClinicosRoute: RelatoriosClinicosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SbLoginRoute: SbLoginRoute,
  SbPacientesRoute: SbPacientesRoute,
  SbSignupRoute: SbSignupRoute,
  SignupRoute: SignupRoute,
  SuperAdminRoute: SuperAdminRoute,
  TratamentosRoute: TratamentosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
